### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#291]
Originally posted to the mailing list here:

https://groups.google.com/d/msg/accelerate-haskell/DNO2kHbr6n0/xJRdNc8BAAAJ

**Comment by tmcdonell** [comment]
What OS are you using? If you are on linux, the [`.travis.yml`](https://github.com/AccelerateHS/accelerate-llvm/blob/master/.travis.yml) file may have some hints for what needs to be installed for everything to work.

I have only tried on llvm-3.4 and llvm-3.5 recently. I am bound by what versions of llvm the `llvm-general` package supports, and how quickly it changes its API.

Can you try building with [`stack`](http://docs.haskellstack.org/en/stable/README.html)? For example:

> stack --stack-yaml=stack-7.8.yaml build

**Comment by villesokk** [comment]
When I use that stack command, it fails when building cuda-0.7.0.0:

Setup.hs:174:44:
        Not in scope: ‘extraGHCiLibs’
        Perhaps you meant ‘extraGHCiLibs_’ (line 173)

**Comment by mwu-tow** [comment]
Cabal 1.18 comes with GHC 7.8.4. As `cuda` needs Cabal 1.22, you need to:
a) if you build with cabal-install, it will use Cabal installed in your user database/sandbox (as Cabal 1.22 is listed as dependency, cabal-install should install it automatically and it should work out-of-the-box)
b) if you use stack, add Cabal 1.22 to your GHC installation by `stack setup 7.8.4 --upgrade-cabal`. You might need to run it with sudo, depending on how is your GHC installed.

**Comment by villesokk** [comment]
It only worked when I built in the accelerate-llvm git checkout folder. When I tried to add accelerate-llvm and accelerate-llvm-native to my project, it still doesn't build. I get an error like this (with stack build --verbose):

```
2015-12-03 21:40:46.706931: [info] accelerate-llvm-2.0.0.0: build @(stack_6NMiBlcabnxAyfVhCxyMn0:Stack.Build.Execute src/Stack/Build/Execute.hs:663:23)
2015-12-03 21:40:46.707132: [debug] Run process: /home/ville/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0 build lib:accelerate-llvm --ghc-options " -ddump-hi -ddump-to-file" @(stack_6NMiBlcabnxAyfVhCxyMn0:Stack.Build.Execute src/Stack/Build/Execute.hs:807:21)
Progress: 1/3
--  While building package accelerate-llvm-2.0.0.0 using:
      /home/ville/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0 build lib:accelerate-llvm --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-4)
    Logs have been written to: /foo/bar/.stack-work/logs/accelerate-llvm-2.0.0.0.log

    Preprocessing library accelerate-llvm-2.0.0.0...
    [ 1 of 44] Compiling Data.Range.Range ( Data/Range/Range.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Data/Range/Range.o )
```

And the log file contains just the end of the error message:

```
Preprocessing library accelerate-llvm-2.0.0.0...
[ 1 of 44] Compiling Data.Range.Range ( Data/Range/Range.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Data/Range/Range.o )
```

I used the following stack.yaml (basically copied from the file in the accelerate-llvm repository):

```
resolver: lts-3.15

packages:
- '.'

- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: e9d8c2f8dc57b369253525987c2a7bc61c58f647
  extra-dep: true

- location:
    git:    https://github.com/bscarlet/llvm-general.git
    commit: 1ee693cc7577aab2f3e11ec9bd7f4244a5182c89
  extra-dep: true
  subdirs:
    - llvm-general

- location:
    git: https://github.com/AccelerateHS/accelerate-llvm
    commit: 11381a72c5378b769b8dbacec7a889e8c69fa62b
  extra-dep: true
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native

extra-deps:
- 'accelerate-2.0.0.0'
- 'accelerate-llvm-2.0.0.0'
- 'accelerate-native-2.0.0.0'
- 'chaselev-deque-0.5.0.5'
- 'llvm-general-3.5.1.0'
- 'llvm-general-pure-3.5.0.0'
- 'libffi-0.1'
```
