### ISSUE TITLE
accelerate-llvm got installed under local directory, not as global stack package

### ISSUE THREAD

**Issue by chmlxj** [AccelerateHS/accelerate#344]
I installed successfully the accelerate-llvm package, but it got installed automatically as a local package. I can not import it when I am working outside the directory.
Any quick fix to this?

**Comment by tmcdonell** [comment]
You can add it as an extra dependency to the `stack.yaml` of the other project you want to use it in. See for example the `stack.yaml` in `accelerate-examples` package [here](https://github.com/AccelerateHS/accelerate-examples/blob/master/stack-8.0.yaml#L19).

Add something like...

```yaml
packages:
- '.'
- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: 4635336aee94c00d5014e5e640753f8f2b2ac21e
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

flags:
  llvm-general:
    shared-llvm: true
```
