### ISSUE TITLE
The following target packages were not found: accelerate-llvm-ptx

### ISSUE THREAD

**Issue by proposition** [AccelerateHS/accelerate#354]
Hello. Can anybody help. I can't install accelerate-llvm and accelerate-llvm. Every time I get that note by **stack**
`The following target packages were not found: accelerate-llvm`
and
`The following target packages were not found: accelerate-llvm-ptx`

**Comment by tmcdonell** [comment]
Unfortunately the `accelerate-llvm*` packages aren't on Hackage/Stackage yet. You can still use them though by adding something like the following to your `stack.yaml` file:

```yaml
- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: fae79cdf4f668c03f84513531cd6059355cb38a4
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'
```

If you are using ghc-8 (recommended) then you'll need to get `llvm-general` from github as well. Check the `stack.yaml` files in the accelerate project repos for more examples of things you might need (e.g. [here](https://github.com/AccelerateHS/accelerate-examples) or [here](https://github.com/tmcdonell-bot/accelerate-travis-buildbot)).

Let me know if you have any problems (:

**Comment by tmcdonell** [comment]
*I recommend ghc-8.0.2, as 8.0.1 has [a bug](https://ghc.haskell.org/trac/ghc/ticket/12573) which could affect you using the PTX backend. At the top of your `stack.yaml` you can:

```yaml
compiler: ghc-8.0.2
```

ghc-7.10.3 also works pretty well.

**Comment by proposition** [comment]
I tryed to use compilers 8.0.2 and 7.10.3 but have no changes. It didn't solve the problem.

**Comment by tmcdonell** [comment]
@proposition please post your `stack.yaml` file and the commands you tried to use to install.

**Comment by proposition** [comment]
With this file i have 
`Process exited with code: ExitFailure 1`

**Comment by proposition** [comment]
With this file I have 
`Process exited with code: ExitFailure 1
 Logs have been written to: /home/nsadykov/.stack/global-project/.stack-work/logs/llvm-general-3.8.0.0.log

    Configuring llvm-general-3.8.0.0...
    Warning: Instead of 'cc-options: -I/usr/local/include' use 'include-dirs:
    /usr/local/include'
    setup: Missing dependency on a foreign library:
    * Missing C library: LLVM-3.8.0
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
`
[mystack.txt](https://github.com/AccelerateHS/accelerate/files/766655/mystack.txt)

**Comment by proposition** [comment]
I used this command
`stack install accelerate-llvm-ptx`

**Comment by tmcdonell** [comment]
Yep, it needs LLVM installed on your system (which shared library) and is looking for that. 

If you have a Debian/Ubuntu system, there are instructions for getting it via apt on http://apt.llvm.org. In summary, you need to do something along the lines of...

$ wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
$ sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main"
$ sudo apt-get install llvm-3.9-dev

If you are not on a ubuntu/debian system, then your package manager still probably includes it. Otherwise, I could help you build llvm from source.

I recommend using llvm-3.9, since that is currently the latest version. Change the `llvm-general` entry in your stack.yaml to:

```yaml
- location:
    git:    https://github.com/bscarlet/llvm-general.git
    commit: ec1ad5bd2112e7f64dbb43441b5e2075cf6ad8e7 # 3.9
  extra-dep: true
  subdirs:
    - 'llvm-general'
    - 'llvm-general-pure'
```

Good luck!
