### ISSUE TITLE
./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9: (unhandled): CUDA Exception: device kernel image is invalid

### ISSUE THREAD

**Issue by ozzzzz** [AccelerateHS/accelerate#386]
Hi, Trevor!
I have error like issue https://github.com/AccelerateHS/accelerate/issues/375, but a little bit different. 
So the error is following:
```
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9: (unhandled): CUDA Exception: device kernel image is invalid
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9 in accelerate-llvm-ptx-1.0.0.0-K9Wf3bmoxEK20Pz9jwFnTj:Data.Array.Accelerate.LLVM.PTX.State
```
nvidia-device-query output can be viewed [here](https://gist.github.com/ozzzzz/4fe641eea458e8f2a1f3b096d9ea0952).

We have:

- CUDA 8.0

- llvm-4.0.0

- cuda-0.7.5.3 library.

- flags:
  llvm-hs:
    shared-llvm: true
  accelerate-llvm-ptx:
    nvvm: false (we tried nvvm: true, the same result)

The problem is that this error occures only in "big" project with a lot of computations. If we make a little example like [here](https://github.com/AccelerateHS/accelerate), everything works fine.

Maybe you know what the problem it can be?

I'll try to make a minimum example to reproduse this problem. Thanks!

**Comment by ozzzzz** [comment]
What I am find, that this message probably from constant CUDA_ERROR_INVALID_IMAGE (see [here](http://horacio9573.no-ip.org/cuda/group__CUDA__TYPES_g0cdead942fd5028d157641eef6bdeeaa.html)). And if I understand it correctly, it should correspond [this](https://github.com/tmcdonell/cuda/blob/master/src/Foreign/CUDA/Driver/Error.chs#L85) line in cuda library.

**Comment by tmcdonell** [comment]
Hi! Having the problem only occur in large programs could make this difficult. At a long shot, could you try my development branch [here](https://github.com/tmcdonell/accelerate-llvm/tree/wip/rtdyld) and let me know if that works?

That is an impressive number of GPUs!

**Comment by ozzzzz** [comment]
Yes, it works!
Thus now I have builded locally accelerate-llvm from [this](https://github.com/tmcdonell/accelerate-llvm/commit/2638493643aec51f635d48aee75ff27c624711ce) commit and following additions to stack.yaml:
```
packages:
- location: <path_to>/accelerate-llvm/accelerate-llvm
- location: <path_to>/accelerate-llvm/accelerate-llvm-ptx
- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: f13c4b549b89aa11388b5f85ec69c7d6cabe5916
  extra-dep: true

extra-deps:
- llvm-hs-4.0.1.0
- llvm-hs-pure-4.0.0.0
- unique-0
- chaselev-deque-0.5.0.5
- linear-accelerate-0.3
- cuda-0.7.5.3
- nvvm-0.7.5.2
```
This are a lot of commits during last master commit. So unfortunately, I do not understand what additions made our day.

Therefore, we are awaiting new accelerate version!

P.S. We have more GPUs that will be use your code, Trevor :)

**Comment by tmcdonell** [comment]
I have attempted to create a fix on the branch here: https://github.com/tmcdonell/accelerate-llvm/tree/hotfix/issue386. If that works for you I can release it immediately as a patch release.

Sorry for the delay, I have been busy in a paper writing crunch.

By the way, I would be interested to hear of your experiences with Accelerate; what works/doesn't work, what you would like added/improved, etc... feel free to contact me directly if you prefer (:

**Comment by ozzzzz** [comment]
Yep, it works! So it will be perfect if you can do a patch release :)

I have some questions, but I think that they are not suitable for this issue)

**Comment by tmcdonell** [comment]
Great! Released as [accelerate-llvm-ptx-1.0.0.1](https://hackage.haskell.org/package/accelerate-llvm-ptx-1.0.0.1).

Feel free to open tickets to ask questions as well as to report issues (:

**Comment by ozzzzz** [comment]
Hi, Trevor!
I have bad news. This night I run test with a lot of computations and found out that computational speed decreased dramatically. I tried to reconstruct previous versions and result is following:

* accelerate ([this version](https://github.com/tmcdonell/accelerate/commit/f13c4b549b89aa11388b5f85ec69c7d6cabe5916)) with accelerate-llvm ([this version](https://github.com/tmcdonell/accelerate-llvm/commit/2638493643aec51f635d48aee75ff27c624711ce)) works fine;

* accelerate-1.0.0.0 with accelerate-llvm ([from this branch](https://github.com/tmcdonell/accelerate-llvm/tree/hotfix/issue386)) works slowly;

* thus accelerate-1.0.0.0 with accelerate-llvm-ptx-1.0.0.1 works slowly too.

I point out that everything compile and work without errors in all versions. The difference in speed (actually, huge difference).

It was *my* fault not to run big test before write that comment ("Yep, it works!...").

**Comment by tmcdonell** [comment]
hmm, that does not sound good at all \\:

Interesting that the [wip/rtdyld](https://github.com/tmcdonell/accelerate-llvm/tree/wip/rtdyld) branch seems to be fine though. I'll have another look through the commits there and see if there are any other relevant commits that I should cherry-pick; otherwise, maybe I will just have to try and finish that branch off quickly and release it completely.

I'll see if I can construct a test program to benchmark this. I'm guessing that the actual kernel time is the same, but the slowdown is in the runtime system somewhere.

sorry for the hassle ):

**Comment by tmcdonell** [comment]
Hi @ozzzzz, sorry for the slow progress. I have finished my development branch and merged that back into master; when you get a chance could you please check that that works correctly for you? Thanks!

tmcdonell/accelerate-llvm@040c33637b670ac6988a96e70241d5eda4a32319

**Comment by ozzzzz** [comment]
Hi @tmcdonell !
I hope that I understood right and made following test environment:

* locally build of accelerate-llmv from commit [040c336](https://github.com/tmcdonell/accelerate-llvm/commit/040c33637b670ac6988a96e70241d5eda4a32319)

* stack.yaml
```
- location: <local/path/to>/accelerate-llvm
- location: <local/path/to>/accelerate-llvm-ptx

- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: be851212c1f5c26e948b85c5e428207c78bdae16
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/cuda.git
    commit: 1bff17152088384b71a439b01ec993a54e2618c9
  extra-dep: true

extra-deps:
#- accelerate-1.0.0.0
#- accelerate-llvm-1.0.0.0
- llvm-hs-4.1.0.0
- llvm-hs-pure-4.1.0.0
- unique-0
- chaselev-deque-0.5.0.5
- linear-accelerate-0.3
#- accelerate-llvm-ptx-1.0.0.1
#- cuda-0.7.5.3
- nvvm-0.7.5.2
```

The result os following: it builds, works. But speed decreased (not so huge as before, but at least 2-5 times).

Also I have something to discuss before the next release will be done. But this is not for public discuss and I'll send them with e-mail.
