### ISSUE TITLE
Smarter in-place permutations

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#432]
I am submitting a...
- [x] bug report (runtime performance)
- [x] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

`permute` can in-place update arrays, but the check for when it is safe to do this is very simple and easily defeated by the way the optimiser will shuffle around pieces of code.

The function [`featureRep`](https://github.com/tsoernes/haskelldca/blob/a5f88c5b5fa65f5744d9809cb033a6df3ac90d63/src/Gridfuncs.hs#L132) from [tsoernes/haskelldca](https://github.com/tsoernes/haskelldca) has a pattern where `permute` is used to update (or generate) an array in several steps. The function (where `rOWS` and `cOLS` has been set to 2) is shown [here](https://gist.github.com/tmcdonell/10d3f5843a24e76916c6ed177aaae218). Note that in the second and subsequent calls to `permute` the destination array is given as an `Avar`, so even though it is only used once and we should update it in-place, it won't be because the check for when this is safe to do is [very simple](https://github.com/tmcdonell/accelerate-llvm/blob/4fc2ddbec764413f95248b10fd089d26b508e89d/accelerate-llvm/src/Data/Array/Accelerate/LLVM/Execute.hs#L420).

## Expected behaviour

Speed.

## Current behaviour

Not speed.

## Possible solution (optional)

- Be smarter about when it is safe to update in-place
- Take special care when fusing `permute` (probably [here](https://github.com/tmcdonell/accelerate/blob/4e6a24f771ade0c577b738ca0eadb6f483a6682f/src/Data/Array/Accelerate/Trafo/Fusion.hs#L200) or [here](https://github.com/tmcdonell/accelerate/blob/4e6a24f771ade0c577b738ca0eadb6f483a6682f/src/Data/Array/Accelerate/Trafo/Fusion.hs#L447)).

## Steps to reproduce (for bugs)

 1.  show `featureRep`
 2.
 3.

## Your environment

- Accelerate version:
- Accelerate backend(s) used:
- GHC version:
- Operating system and version:
- Link to your project/example: https://github.com/tsoernes/haskelldca
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

**Comment by tmcdonell** [comment]
For reference here's the stack.yaml I used to build HEAD:

```yaml
# work-dir: .stack-work-head

resolver: nightly-2018-10-08  # ghc-8.6.1
# resolver: lts-12.10           # ghc-8.4.2

packages:
- .

extra-deps:
- git:    https://github.com/tmcdonell/accelerate.git
  commit: 4e6a24f771ade0c577b738ca0eadb6f483a6682f

- git:    https://github.com/tmcdonell/accelerate-llvm.git
  commit: 3e6de77da9dd5d3dc6969ad8251b94da557e5479
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native

- git:    https://github.com/tmcdonell/accelerate-blas.git
  commit: 2f8d66d1d1df9345263d70fefd1b3dfec0fa4336

- git :   https://github.com/llvm-hs/llvm-hs.git
  commit: 1e512dcf2a40d253a95d231b7991b48f1f2a8a9e
  subdirs:
    - llvm-hs
    - llvm-hs-pure

- lens-accelerate-0.2.0.0
# - primitive-0.6.4.0

flags:
  accelerate-blas:
    llvm-ptx: false
  accelerate:
    debug: true
    nofib: false

ghc-options:
  "$locals":  -O2 -threaded -rtsopts
  "$targets": -O2 -threaded -rtsopts
#   accelerate: -O2 -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-n2M -with-rtsopts=-A64M
#   accelerate-llvm-native: -O2 -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-n2M -with-rtsopts=-A64M

# vim: nospell
```
